name: Nuclei DAST Scan (Docker)

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  nuclei-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run Nuclei scan with Docker (raw requests)
        run: |
          mkdir -p scans
          # Scan POST request
          docker run --rm -v $PWD:/root/project projectdiscovery/nuclei:latest \
            -raw /root/project/addUser.req \
            -json-export /root/project/scans/addUser-report.json
          
          # Scan GET request
          docker run --rm -v $PWD:/root/project projectdiscovery/nuclei:latest \
            -raw /root/project/account.req \
            -json-export /root/project/scans/account-report.json

      - name: Upload scan reports
        uses: actions/upload-artifact@v4
        with:
          name: nuclei-reports
          path: scans/
